/**
 * This file is part of RibbonClient application (check README).
 * Copyright (C) 2013 Stanislav Nepochatov
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
**/

package ribbonclient;

/**
 * Realease frame class;
 * @author Stanislav Nepochatov
 */
public class releaseDialog extends javax.swing.JDialog {
    
    /**
     * Message to release;
     */
    private MessageClasses.Message currMessage;
    
    /**
     * Current mode of parent editor;
     */
    private editorFrame.editMode currMode;

    /**
     * Creates new form releaseDialog
     */
    public releaseDialog(java.awt.Frame parent, boolean modal, MessageClasses.Message givenMessage, editorFrame.editMode givenMode) {
        super(parent, modal);
        initComponents();
        currMessage = givenMessage;
        currMode = givenMode;
        this.dirIndicator.setText(Generic.CsvFormat.renderGroup(currMessage.DIRS));
        this.langBox.setSelectedItem(currMessage.LANG);
        this.dirTree.setModel(DirEntrySW.rootDir);
        dirTree.expandRow(0);
        dirTree.setRootVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dirTree = new javax.swing.JTree();
        jLabel1 = new javax.swing.JLabel();
        dirIndicator = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        langBox = new javax.swing.JComboBox();
        cancelBut = new javax.swing.JButton();
        releaseBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Випуск повідомлення");
        setResizable(false);

        dirTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                dirTreeValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(dirTree);

        jLabel1.setText("Обрані напрямки");

        dirIndicator.setEditable(false);

        jLabel2.setText("Мова повідомлення");

        langBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UA", "RU", "EN", "ES", "DE", "UKN" }));

        cancelBut.setText("Скасувати");
        cancelBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButActionPerformed(evt);
            }
        });

        releaseBut.setForeground(new java.awt.Color(153, 0, 0));
        releaseBut.setText("Випустити");
        releaseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                releaseButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dirIndicator)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(langBox, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 137, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(releaseBut)
                        .addGap(18, 18, 18)
                        .addComponent(cancelBut)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dirIndicator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(langBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelBut)
                            .addComponent(releaseBut)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dirTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_dirTreeValueChanged
        javax.swing.tree.TreePath[] pathes = dirTree.getSelectionPaths();
        String[] dirStrings = new String[pathes.length];
        for (Integer selIndex = 0; selIndex < pathes.length; selIndex++) {
            dirStrings[selIndex] = DirEntrySW.getEndDir(pathes[selIndex]).FULL_DIR_NAME;
        }
        this.dirIndicator.setText(Generic.CsvFormat.renderGroup(dirStrings));
    }//GEN-LAST:event_dirTreeValueChanged

    private void cancelButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButActionPerformed

    private void releaseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_releaseButActionPerformed
        String command = null;
        switch (currMode) {
            case POST:
                command = "RIBBON_POST_MESSAGE:-1," + this.dirIndicator.getText() + "," + ((String)this.langBox.getSelectedItem()) + ",{" +
                this.currMessage.HEADER + "}," + Generic.CsvFormat.renderGroup(currMessage.TAGS) + "\n" + currMessage.CONTENT + "\nEND:";
                break;
            case MODIFY:
                command = "RIBBON_MODIFY_MESSAGE:" + currMessage.INDEX + "," + this.dirIndicator.getText() + "," + 
                ((String)this.langBox.getSelectedItem()) + ",{" + currMessage.HEADER + "}," + Generic.CsvFormat.renderGroup(currMessage.TAGS) + 
                "\n" + currMessage.CONTENT + "\nEND:";
                break;
            case RE_POST:
                command = "RIBBON_POST_MESSAGE:" + currMessage.ORIG_INDEX + "," + this.dirIndicator.getText() + "," + ((String)this.langBox.getSelectedItem()) + ",{" +
                this.currMessage.HEADER + "}," + Generic.CsvFormat.renderGroup(currMessage.TAGS) + "\n" + currMessage.CONTENT + "\nEND:";
                break;
        }
        String result = RibbonClient.ClientApplication.appWorker.sendCommandWithReturn(command);
        if (result.startsWith("OK:")) {
            this.dispose();
        } else {
            RibbonClient.ClientApplication.reportError(result);
        }
    }//GEN-LAST:event_releaseButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(releaseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(releaseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(releaseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(releaseDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                releaseDialog dialog = new releaseDialog(new javax.swing.JFrame(), true, new MessageClasses.Message(), editorFrame.editMode.POST);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBut;
    private javax.swing.JTextField dirIndicator;
    private javax.swing.JTree dirTree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox langBox;
    private javax.swing.JButton releaseBut;
    // End of variables declaration//GEN-END:variables
}
